## Pruebas de tiempo con Numpy

In [230]:
num = 1_000_000

In [231]:
xs = list(range(num))
ys = list(range(1, num+1))

In [232]:
import math

In [233]:
def disteuc(xs,ys):
    sum = 0
    for x, y in zip(xs, ys):
        sum += (x-y)*(x-y)
        
    return math.sqrt(sum)

In [234]:
%time disteuc(xs,ys)

CPU times: user 188 ms, sys: 0 ns, total: 188 ms
Wall time: 188 ms


1000.0

In [235]:
import numpy as np
xs2 = np.arange(num)
ys2 = np.arange(1, num+1)

In [236]:
def disteucnp(xs,ys):
    z = (xs-ys)
    return math.sqrt((z*z).sum())

In [237]:
%time disteucnp(xs2,ys2)

CPU times: user 4 ms, sys: 4 ms, total: 8 ms
Wall time: 6.3 ms


1000.0

## Otra prueba, detectando si alguien gana

In [238]:
tam=15

In [239]:
dist = np.random.randint(1, 30, size=tam*tam).reshape((tam,tam))
dist[np.arange(tam),np.arange(tam)] = 0
sol = np.random.permutation(tam)
print(dist)
print("Solución:", sol)

[[ 0 14 19 10  2 28  4 23 12 26 27 29 19 27 12]
 [12  0  3 24 20 26 24 21  1 19 16 24 23  8  2]
 [ 8 26  0 18 29 26 27 24 12  6 14  9 16 21 15]
 [16  1 17  0 27 23  3 21 21  8 27  1  8  1 24]
 [ 3 29  7 20  0 24 17  9 20 23 20  2 25 27 12]
 [ 9 20  6 19 11  0 22 12 18 17  7 21 23  3 22]
 [24 29  5 12 20 24  0 29 18 28  2  8 22 23  1]
 [ 5 20  9 20  6 19 24  0 19  2 23  3 16 22 22]
 [14  7  9  3 12 29 21  7  0  5  8 26 21 10 24]
 [ 3 17  6 29 19  3 22  7  8  0 10 20 15  9 29]
 [29 11 21 27 18  7 10 14 14 18  0 22 22 15 22]
 [16  8 17  2 29 14 13 24 19 10 12  0 13  8 24]
 [29 20 11 15 24 15  7 27 14 21 19 18  0 29  3]
 [ 5 25 15  3 29 13 13 26 17 27  1 22  7  0 20]
 [ 4  4 14 13  9  9  6 23  5 14 19 24 15 15  0]]
Solución: [ 6 14  7 13 11 10  5  2 12  8  0  1  9  4  3]


In [240]:
def tsp(orden, dist):
    sum = 0
    
    for i in range(len(orden)-1):
        sum += dist[orden[i]][orden[i+1]]
   
    sum += dist[orden[-1]][orden[0]]
    return sum

In [241]:
dist_raw = dist.tolist()
sol_raw = sol.tolist()

In [242]:
%timeit tsp(sol_raw,dist_raw)

100000 loops, best of 3: 2.7 µs per loop


In [243]:
total=tsp(sol_raw,dist_raw)
total

212

In [244]:
desp = np.roll(sol,-1)
print(sol)
print(desp)
dist[sol,desp].sum()

[ 6 14  7 13 11 10  5  2 12  8  0  1  9  4  3]
[14  7 13 11 10  5  2 12  8  0  1  9  4  3  6]


212

In [245]:
def tsp_np(sol, dist):
    desp = np.roll(sol,-1)
    return dist[sol,desp].sum()

In [249]:
desp = np.roll(sol,-1)
%timeit dist[sol,desp].sum()

The slowest run took 37.76 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3 µs per loop
